#!/usr/bin/env bash

pacman -S yay
pacman -S vim
pacman -S fish
pacman -S ranger
pacman -S ripgrep
pacman -S doublecmd-gtk2
pacman -S spotify
pacman -S keepassxc
pacman -S steam-manjaro
pacman -S telegram-desktop
pacman -S lib32-libxrandr
pacman -S lib32-openal
pacman -S clojure
pacman -S dotnet-sdk
yay -S google-chrome
yay -S redshift-gtk-git
yay -S dropbox
yay -S simplenote-electron-bin
yay -S skypeforlinux-stable-bin
yay -S jetbrains-toolbox
yay -S caprine
yay -S freeoffice
yay -S slack-desktop
yay -S paper-icon-theme-git
yay -S visual-studio-code-bin
yay -S leiningen
yay -S leiningen-completions
