#!/usr/bin/env bash

pacman -S yay
pacman -S vim
pacman -S atom
pacman -S fish
pacman -S ripgrep
pacman -S mc
pacman -S ranger
pacman -S neofetch
pacman -S doublecmd-gtk2
pacman -S spotify
pacman -S keepassxc
pacman -S steam-manjaro
pacman -S telegram-desktop
pacman -S clojure
pacman -S dotnet-sdk
pacman -S papirus-icon-theme
pacman -S ttf-roboto
pacman -S lxappearance-gtk3
pacman -S lib32-libxrandr
pacman -S lib32-openal
pacman -S wmctrl
yay -S oh-my-zsh-git
yay -S google-chrome
yay -S dropbox
yay -S simplenote-electron-bin
yay -S skypeforlinux-stable-bin
yay -S jetbrains-toolbox
yay -S caprine
yay -S freeoffice
yay -S slack-desktop
yay -S visual-studio-code-bin
yay -S leiningen
yay -S leiningen-completions
yay -S redshift-gtk-git
#yay -S xflux
#yay -S xflux-gui-git
yay -S xseticon